# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backEnd?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 8181

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8181
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:8181

markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization